### ISSUE TITLE
Better example needed / possible issue on OSX

### ISSUE THREAD

**Issue by ghost** [pigulla/grunt-encoding#1]
Running on OSX 10.7 and tried following your example - my understanding being it would convert the encoding of all src files to UTF8.

However when running grunt task I get the following warning:
Warning: iconv does not support encoding "UTF-8" Use --force to continue.

If I join your encodings array into a string and use inside of assertEncodingSupport it seems to get a step further, and correctly identify two files that need converting, but it doesn't actually convert them, it throws the following error: 

Warning: 2 files are not encoded correctly Use --force to continue.

my grunt config includes the following:

```
encoding: {
  options: {
    encoding: 'UTF-8'
  },
  files: {
    src: ['public/data/*.csv'],
  },
}
```

**Comment by iweindesmedt** [comment]
solved this by adding these lines in the ```assertEncodingSupport``` function before the check:
```
encodings = ' ' + encodings.join(' ') + ' ';
encoding = ' ' + encoding + ' ';
```

that's because --list outputs 'UTF-8 UTF8' on 1 single line, as it does other encodings

**Comment by pigulla** [comment]
For 0.3.0, I've rewritten the code that determines whether an encoding is supported or not. I used to parse the output of `iconv --list` which is problematic for a number of different reason. Instead, I now simply run iconv with the specified encoding and see if it returns an error. Much simpler and less error prone.
